# CharlypAutocompleteBundle demo routes
_autocomplete:
    pattern:  /autocomplete
    defaults: { _controller: charlyp_autocomplete.controller.demo:autocompleteAction }

_get_json:
    pattern:  /get-json
    defaults: { _controller: charlyp_autocomplete.controller.demo:getJsonAction }

_homepage:
    pattern: /
    defaults: { _controller: frameworkBundle:Redirect:Redirect, route: _autocomplete }
